version: "3.9"

services:
  registry-service:
    build: 
      context: ./registry_service
    env_file:
      - ./registry_service/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./registry_service:/app
    command: >
      sh -c "
      alembic upgrade head && 
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  bff-service:
    build:  
      context: ./BFF    
    env_file:
      - ./BFF/.env
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
    volumes:
      - ./BFF:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000


  validator-service:
    build:  
      context: ./validator_service
    env_file:
      - ./validator_service/.env
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
    volumes:
      - ./validator_service:/app
    command: faststream run app.main:app --host 0.0.0.0 --port 8000

  
  db:
    image: postgres:15
    container_name: access_control_service_db
    env_file:
      - ./registry_service/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


volumes:
  postgres_data:
  rabbitmq-data: